sudo: false
language: scala
jdk: oraclejdk8
scala:
- 2.12.8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt -name "*.lock" -print -delete
- rm -f $HOME/.ivy2/.sbt.ivy.lock
before_install:
- |
  if [[ $TRAVIS_PULL_REQUEST == false ]]; then
    openssl aes-256-cbc -K $encrypted_ecabeeb9cb0c_key -iv $encrypted_ecabeeb9cb0c_iv -in secrets.tar.enc -out local.secrets.tar -d;
    tar xv -C travis -f travis/local.secrets.tar;
  fi
after_success:
- |-
  if [[ $TRAVIS_PULL_REQUEST == false ]]; then
    sbt ++$TRAVIS_SCALA_VERSION publishSigned;
  fi
env:
  global:
  - secure: FGDuA5NMEVhSNjZyYLk+ggLvZjPP/zPiPxcSvEDrm0bIdFAvULSFyJxMeiVYJym+rKnBGiKEyCeWN5LYbxQtGxmlv4wloIowbLNhFx2c7qYZrCN0iCxnohhtpxQdRIHE2VZ8Yn1n8BzX5pLEkVX428xWOd07juMZd1opzWcy3RpQZiORxQ7LW9LHj4hPU/Yf/Z6WovXcwC6guRmw1lESa8hCaLdJvrwI50oZBQ5Gw5m/15pdArwu1FcxIn/AdEUmg2qOlOnkVZdkWNLcrsh7W8GNs2vMzN9vlGyCOrLvMR9nJ6xsNcoZ2gUnHR0U60b5N0t6m6+FmNeTRg5I1SZKbb4dItNd4m+NLq0J81QE0FBa/ltwfKTceNcCYyc+V8fKgCsQ7QU1JFbHVcQSwS7xAaXeH5nmySxWPK1S1pSm+dvoxV+ZR4uZ2NgrxpGPrICDak8v/lXbB7eexyScL8SEFmbbhWpRR65jYLvEXlmOchsdhe6cIZJBZ5OO4HN25NL0/aPWRS+S59Qf0LHmJ0FB/5HQmRzijiQGuWYPyt0OAbAzaCi+ctw/lUaebsdOIPLF3KIpTKOtZT2kKlckIYs55v0FGK5vDOk5wWCc14dvrJMItp7vCF5Oh4zZQZSPW//TxJ7JuGlZ03ebvpZ5vCmS/RvP4qR2+YL8O03RfsMi+EA=
  - secure: dy9LZ9AgeYKfnDaNw1ITRyxvgff9BckfZZeytI+r46ovYRcCJXYVrbP14bgxxlWkYLXGzPPMrUlwFQGsnKLbQfua32zUrhfGoyylMMlFXDLqGeqX6WRF1qBDvOs1gupZ//Ja93+2c7EVlgszE+t+WECy1oFVv2ARrcChV7+ILceNx78Hx6BYHvyFq4CvoOQ7CCYuEzHB8QxzFdgu5La0uqMOlJhZ1qXov0/f0TYMNWxVgy6n6SWRy/5y7zBJQ/kqBlAocx9GirXm7OuksoDJGXfq00TLAj1A+vI4YxWyHoNw1yP8QqgF3q+jqr3DQGJlxL3O1y3LCx+xBSgUIDBdTOkxlmsKIB5P/zdB2qCbHfqSVPi5BCYOxXrt2ia8dILz3+En4eXYpzGuYo7re6LJofy1f6DBmVyRLNHKSu5m8Yoy6TtUGMqfZj+s9bGWLhL2f3azbuCtdzMJDtH2vbkNvsGP0WqxIyXivBGijBJ3KkWqF9rH5lXSuNPHDVL0lmmsL8AztU9vdEjB84IreFDSmR3+2l2mRdXRwEajNU0RhHoMuFLXYYanDljrHEir2YwYr/1ji8Zyl6rWKMv5VgdDnj6AWrRDvInpnKsvByBY1/3Dn7J8S1OAi6N/xClLgz1O/6zHWX1E7JmgFQguA5tLMiPiUyONDGKh5B7ZJptM6WM=
  - secure: A6Mk4mI0dHS0Hb+bxpoOTVNkjnx4RSv433iiBTqmrr3Wgl7nsbI4Hv8LXYc6d1YRP5JL/wQvcz/rH6+Ml5s4XYcpP/jYstBKfdKKLuGqjQf1KLZ3Jk0gRvlnKAE2j2sWvrhSOVQnEQXRiuKO6UKT4LsZz7GuWZ9+BayBYOOAnrDuOUMKp5uaFGW991HvbXiJtj/KRGHyMlpQEVrRAcDyA/vDRhEm7OUcxs7Z1YaSQGODrhBl55oIYXIQIwZDU0Sp/JpczyjGVhApAvjIs+crAW3ZYm1T4gsQqTWGJe7Eqsibej+7Mu1lvzdb1wsAJkDE1Y2MVbAp9lSr/lXCP62wu+cSfoYL5P8sk19tVrqEF9dr6fiQeGy7ANAwvHTXRey6mve4sGnAkJdYJy+OEqlr/Y54eXS+JPGQ6psZu5UpSs022BK4slcjjhWp7iUU3c9tHFKvSgHrL88I1xTNBy/CQ4Wk2mMirBzx+RlwoweNEpGw1Vcj7Alwm4SkreslQPRqUxSLm7R809BTtIf4nEKQDI9XHl2cJPUJERFUCnWFl+nsJM1FZ41CAL3RZ9z10NplYte0p90N0yY+OEnVadc1GOYRQw98/eq4dq31evp4OClaPhXoNnBMCFKTCZqSwRjdMjHk1oUZ2AR57AbfiqqILojGG582IRrTl+4ZXKzelRA=
  - secure: Z8F3+JJMokNNPov56ey8NBrrJPj48yF8ICjs9J7188cdWFupK2orCr5lvJa0AeWEpJ4g3omMOxo0s1wzS24Wt3MXpjTCoCoq5iuHmD/0RrFPbwhHTluUjDJBHTBjRb22hSJmcBMiNVaXE2CjYdVnoEFKt1RhFplVp/dj6bOFIPuEp02rMutg9zlqU0VoU9dQ6pfQcWQnt7tyFKs1dpTKJlQmia6GB7qBXgu/29LoEQpNa4aFU7x9QOXRhATo6KdyC4naR0FJ5O9QkAdZb7Tr1D+dJ+mzMBh6d9+bjs3QYs63I2PW94jOGBTPRaIKRCWToRQVJ7YM4sCDJlQFdXylyhlnR7MvtX9oo3luULJRzTkF5ikWF+CtTjasoBYVAeNthFXURY+CUYJNJ2EnKkLBoql14kbQyNnCIMTm5tguJVT3TTYsrx/VZmUYufuVGEUS3HkSYCyjyj4aEG9gnbeGxfyRj+s5kAFkYilLi5qVRUiOrraK1368+rFHu6YIxhmUaSk+8ThETVpQ7Q3OMB/xUAob6GRbBLaUBX1EMmeGRNlmI9eX4Q09cZszlNilkrqiIO+zWZqT9e4K7odpr9CtuQm4HH0aCDsnumzD8CZqlSBFLCjTdUXvrlNA4elmzgiXKeqCUVKlF75eTwV9sF9ANU0cfTLWjZjUXEISyT/Di20=
